### ISSUE TITLE
failed to cargo install

### ISSUE THREAD

**Issue by laoshaw** [chrisvest/xv#24] opened 2022-02-23 14:52 UTC
```
error[E0432]: unresolved import `syn::export`
  --> /home/laoshaw/.cargo/registry/src/github.com-1ecc6299db9ec823/enumset_derive-0.4.4/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `enumset_derive` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `xxv v0.1.2`, intermediate artifacts can be found at `/tmp/cargo-installohZX3q`

Caused by:
  build failed
     Failed to install xxv (see error(s) above).
```

**Comment by chrisvest** [comment] 2022-02-23 15:43
Use `cargo install xxv --locked`

Dupe of #22

**Closed as completed by chrisvest** 2022-02-23 15:43 UTC
